display_name: Terrestrial Forest Monitor
package_name: tfm

maintainer:
  name: Thünen Institute
  email: karsten.dunger@thuenen.de

priority: optional

section: x11

installed_size: 15700

dependencies:
  - mpv

essential: false

icon: assets/logo/tfm.png

postuninstall_scripts:
  - echo "Sorry to see you go."

keywords:
  - TFM
  - Terrestrial Forest Monitor
  - Thünen Institute
  - Forest Monitoring
  - Forest Inventory

generic_name: API Client

categories:
  - Utility

startup_notify: true