# The value of AppId uniquely identifies this application.
# Do not use the same AppId value in installers for other applications.
app_id: 5B599538-42B1-4826-A479-AF079F21A65D
publisher: Thünen Institute
publisher_url: https://www.thuenen.de/de/fachinstitute/waldoekosysteme
display_name: Terrestrial Forest Monitor
create_desktop_icon: true
# See: https://jrsoftware.org/ishelp/index.php?topic=setup_defaultdirname
# install_dir_name: "D:\\HELLO-WORLD"
locales:
  - en
  - de